[Package]
category = "perl"
name = "AnyEvent"
version = "7.12"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Canary-Stability]
version = "2011"
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Async-Interrupt]
version = "1.21"
[Prereqs.perl.runtime.EV]
version = 4.22
[Prereqs.perl.runtime.Guard]
version = "1.023"
[Prereqs.perl.runtime.JSON]
version = "2.90"
[Prereqs.perl.runtime.JSON-XS]
version = 3.02
[Prereqs.perl.runtime.Net-SSLeay]
version = "1.74"
[Prereqs.perl.runtime.Task-Weaken]
version = "1.04"
[Prereqs.perl.test]
