[Package]
category = "perl"
name = "Class-Accessor-Chained"
version = "0.01"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Class-Accessor]
version = "0"
