[Package]
category = "perl"
name = "File-HomeDir"
version = "1.00"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Carp]
version = "1.38"
[Prereqs.perl.runtime.File-Path]
version = "2.12"
[Prereqs.perl.runtime.File-Temp]
version = "0.2304"
[Prereqs.perl.runtime.File-Which]
version = "1.21"
[Prereqs.perl.runtime.PathTools]
version = "3.62"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
