[Package]
category = "perl"
name = "namespace-clean"
version = "0.27"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.B-Hooks-EndOfScope]
version = "0.21"
[Prereqs.perl.runtime.Package-Stash]
version = "0.37"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
