[Package]
category = "perl"
name = "DateTime-Format-ISO8601"
version = "0.08"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Module-Build]
version = "0.4218"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.DateTime]
version = "1.28"
[Prereqs.perl.runtime.DateTime-Format-Builder]
version = "0.81"
[Prereqs.perl.runtime.File-Find-Rule]
version = "0.34"
[Prereqs.perl.runtime.Test-Distribution]
version = "2.00"
[Prereqs.perl.runtime.Test-Pod]
version = "1.51"
[Prereqs.perl.test]
