[Package]
category = "perl"
name = "strictures"
version = "2.000003"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.bareword-filehandles]
version = "0"
[Prereqs.perl.runtime.indirect]
version = "0"
[Prereqs.perl.runtime.multidimensional]
version = "0"
