[Package]
category = "perl"
name = "MooseX-RelatedClassRoles"
version = "0.004"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Moose]
version = "2.1806"
[Prereqs.perl.runtime.MooseX-Role-Parameterized]
version = "1.09"
