[Package]
category = "perl"
name = "Pithub"
version = "0.01033"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Array-Iterator]
version = "0"
[Prereqs.perl.runtime.Cache-LRU]
version = "0.04"
[Prereqs.perl.runtime.HTTP-Message]
version = "0"
[Prereqs.perl.runtime.JSON-MaybeXS]
version = "1.003008"
[Prereqs.perl.runtime.LWP-Protocol-https]
version = "0"
[Prereqs.perl.runtime.Moo]
version = "2.002004"
[Prereqs.perl.runtime.libwww-perl]
version = "0"
