[Package]
category = "perl"
name = "Net-SSLeay"
version = "1.74"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.MIME-Base64]
version = "3.15"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
