[Package]
category = "perl"
name = "PPI"
version = "1.220"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Clone]
version = "0.38"
[Prereqs.perl.runtime.Digest-MD5]
version = "2.55"
[Prereqs.perl.runtime.IO-String]
version = "1.08"
[Prereqs.perl.runtime.List-MoreUtils]
version = "0.415"
[Prereqs.perl.runtime.Params-Util]
version = "1.07"
[Prereqs.perl.runtime.PathTools]
version = "3.62"
[Prereqs.perl.runtime.Scalar-List-Utils]
version = "1.45"
[Prereqs.perl.runtime.Storable]
version = "2.51"
[Prereqs.perl.runtime.Task-Weaken]
version = "1.04"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
