[Package]
category = "perl"
name = "Pod-Coverage"
version = "0.23"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Devel-Symdump]
version = "2.17"
[Prereqs.perl.runtime.Pod-Parser]
version = "1.63"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.test]
