[Package]
category = "perl"
name = "IO-HTML"
version = "1.001"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Carp]
version = "1.38"
[Prereqs.perl.runtime.Encode]
version = "2.84"
[Prereqs.perl.runtime.Exporter]
version = "5.72"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.File-Temp]
version = "0.2304"
[Prereqs.perl.test.Scalar-List-Utils]
version = "1.45"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
