[Package]
category = "perl"
name = "Digest"
version = "1.17"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "0"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.MIME-Base64]
version = "0"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302059"
