[Package]
category = "perl"
name = "Plack-Middleware-ServerStatus-Lite"
version = "0.34"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.CPAN-Meta]
version = "2.150005"
[Prereqs.perl.configure.Module-Build]
version = "0.4218"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Getopt-Long]
version = "2.48"
[Prereqs.perl.runtime.JSON]
version = "2.90"
[Prereqs.perl.runtime.Net-CIDR-Lite]
version = "0.21"
[Prereqs.perl.runtime.Parallel-Scoreboard]
version = "0.07"
[Prereqs.perl.runtime.Plack]
version = "1.0039"
[Prereqs.perl.runtime.Pod-Usage]
version = "1.69"
[Prereqs.perl.runtime.Try-Tiny]
version = "0.24"
[Prereqs.perl.runtime.parent]
version = "0.234"
[Prereqs.perl.test]
[Prereqs.perl.test.Capture-Tiny]
version = "0.42"
[Prereqs.perl.test.Starman]
version = "0.4014"
[Prereqs.perl.test.Test-SharedFork]
version = "0.35"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.Test-TCP]
version = "2.16"
[Prereqs.perl.test.libwww-perl]
version = "6.15"
