[Package]
category = "perl"
name = "Module-Pluggable"
version = "5.2"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Exporter]
version = "5.72"
[Prereqs.perl.runtime.Module-Runtime]
version = "0.014"
[Prereqs.perl.runtime.PathTools]
version = "3.62"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.runtime.perl_mlb]
version = 0
[Prereqs.perl.test]
[Prereqs.perl.test.Data-Dumper]
version = "2.154"
[Prereqs.perl.test.File-Path]
version = "2.12"
[Prereqs.perl.test.File-Temp]
version = "0.2304"
[Prereqs.perl.test.PathTools]
version = "3.62"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.base]
version = "2.23"
[Prereqs.perl.test.perl]
version = "5.024000"
