[Package]
category = "perl"
name = "Test-YAML"
version = "1.06"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Test-Base]
version = "0.88"
[Prereqs.perl.test]
