[Package]
category = "perl"
name = "Test-Base"
version = "0.88"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Filter]
version = "1.55"
[Prereqs.perl.runtime.Spiffy]
version = "0.46"
[Prereqs.perl.runtime.Test-Deep]
version = "1.120"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Algorithm-Diff]
version = "1.1903"
[Prereqs.perl.test.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.test.Text-Diff]
version = "1.44"
