[Package]
category = "perl"
name = "Authen-Simple-Passwd"
version = "0.6"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Authen-Simple]
version = "0.5"
[Prereqs.perl.runtime.IO]
version = "1.25"
[Prereqs.perl.test]
