[Package]
category = "perl"
name = "Plack"
version = "1.0039"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.configure.File-ShareDir-Install]
version = "0.10"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Apache-LogFormat-Compiler]
version = "0.33"
[Prereqs.perl.runtime.CGI-Compile]
version = "0.21"
[Prereqs.perl.runtime.CGI-Emulate-PSGI]
version = "0.21"
[Prereqs.perl.runtime.Cookie-Baker]
version = "0.06"
[Prereqs.perl.runtime.Devel-StackTrace]
version = "2.01"
[Prereqs.perl.runtime.Devel-StackTrace-AsHTML]
version = "0.15"
[Prereqs.perl.runtime.FCGI]
version = "0.78"
[Prereqs.perl.runtime.FCGI-ProcManager]
version = "0.25"
[Prereqs.perl.runtime.File-ShareDir]
version = "1.102"
[Prereqs.perl.runtime.Filesys-Notify-Simple]
version = "0.12"
[Prereqs.perl.runtime.HTTP-Body]
version = "1.22"
[Prereqs.perl.runtime.HTTP-Headers-Fast]
version = "0.20"
[Prereqs.perl.runtime.HTTP-Message]
version = "6.11"
[Prereqs.perl.runtime.HTTP-Tiny]
version = "0.058"
[Prereqs.perl.runtime.Hash-MultiValue]
version = "0.16"
[Prereqs.perl.runtime.IO-Handle-Util]
version = "0.01"
[Prereqs.perl.runtime.Pod-Usage]
version = "1.69"
[Prereqs.perl.runtime.Stream-Buffered]
version = "0.03"
[Prereqs.perl.runtime.Test-TCP]
version = "2.16"
[Prereqs.perl.runtime.Try-Tiny]
version = "0.24"
[Prereqs.perl.runtime.URI]
version = "1.71"
[Prereqs.perl.runtime.libwww-perl]
version = "6.15"
[Prereqs.perl.runtime.parent]
version = "0.234"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Authen-Simple-Passwd]
version = "0.6"
[Prereqs.perl.test.CGI-Compile]
version = "0.21"
[Prereqs.perl.test.CGI-Emulate-PSGI]
version = "0.21"
[Prereqs.perl.test.HTTP-Request-AsCGI]
version = "1.2"
[Prereqs.perl.test.HTTP-Server-Simple-PSGI]
version = "0.16"
[Prereqs.perl.test.IO-Handle-Util]
version = "0.01"
[Prereqs.perl.test.LWP-Protocol-http10]
version = "6.03"
[Prereqs.perl.test.Log-Log4perl]
version = "1.47"
[Prereqs.perl.test.MIME-Types]
version = "2.13"
[Prereqs.perl.test.Module-Refresh]
version = "0.17"
[Prereqs.perl.test.Test-Requires]
version = "0.10"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.libwww-perl]
version = "6.15"
