[Package]
category = "perl"
name = "DBIx-Class"
version = "0.082840"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Class-Accessor-Grouped]
version = "0.10012"
[Prereqs.perl.runtime.Class-C3-Componentised]
version = "1.001000"
[Prereqs.perl.runtime.Class-Inspector]
version = "1.28"
[Prereqs.perl.runtime.Config-Any]
version = "0.27"
[Prereqs.perl.runtime.Context-Preserve]
version = "0.01"
[Prereqs.perl.runtime.DBI]
version = "1.636"
[Prereqs.perl.runtime.Data-Dumper-Concise]
version = "2.022"
[Prereqs.perl.runtime.Data-Page]
version = "2.02"
[Prereqs.perl.runtime.Devel-GlobalDestruction]
version = "0.13"
[Prereqs.perl.runtime.Hash-Merge]
version = "0.200"
[Prereqs.perl.runtime.MRO-Compat]
version = "0.12"
[Prereqs.perl.runtime.Module-Find]
version = "0.13"
[Prereqs.perl.runtime.Moo]
version = "2.002004"
[Prereqs.perl.runtime.Path-Class]
version = "0.37"
[Prereqs.perl.runtime.SQL-Abstract]
version = "1.81"
[Prereqs.perl.runtime.Scope-Guard]
version = "0.21"
[Prereqs.perl.runtime.Sub-Name]
version = "0.21"
[Prereqs.perl.runtime.Try-Tiny]
version = "0.27"
[Prereqs.perl.runtime.namespace-clean]
version = "0.27"
