[Package]
category = "perl"
name = "Test-Time"
version = "0.04"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Filter]
version = "1.55"
[Prereqs.perl.test]
