[Package]
category = "perl"
name = "WWW-Pastebin-PastebinCom-Create"
version = "1.003"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Module-Build]
version = "0"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Moo]
version = "2.002004"
[Prereqs.perl.runtime.WWW-Mechanize]
version = "1.82"
