[Package]
category = "perl"
name = "Lexical-SealRequireHints"
version = "0.010"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Module-Build]
version = "0.4218"
[Prereqs.perl.configure.perl]
version = "5.024000"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.XSLoader]
version = "0.20"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
