[Package]
category = "perl"
name = "Cookie-Baker"
version = "0.06"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Module-Build]
version = "0.4218"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Cookie-Baker-XS]
version = "0.06"
[Prereqs.perl.runtime.Exporter]
version = "5.72"
[Prereqs.perl.runtime.URI]
version = "1.71"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.Test-Time]
version = "0.04"
