[Package]
category = "perl"
name = "JSON-XS"
version = 3.02
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Canary-Stability]
version = "0"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Types-Serialiser]
version = "0"
[Prereqs.perl.runtime.common-sense]
version = "0"
