[Package]
category = "perl"
name = "Net-Ping"
version = "2.41"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Socket]
version = "2.021"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.runtime.Time-HiRes]
version = "1.9733"
[Prereqs.perl.test]
