[Package]
category = "perl"
name = "Test-Most"
version = "0.34"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Exception-Class]
version = "1.40"
[Prereqs.perl.runtime.Test-Deep]
version = "1.120"
[Prereqs.perl.runtime.Test-Differences]
version = "0.64"
[Prereqs.perl.runtime.Test-Exception]
version = "0.43"
[Prereqs.perl.runtime.Test-Harness]
version = "3.36"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.runtime.Test-Warn]
version = "0.30"
[Prereqs.perl.test]
