[Package]
category = "perl"
name = "Net-OpenID-Common"
version = "1.20"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Crypt-DH-GMP]
version = "0.00012"
[Prereqs.perl.runtime.HTML-Parser]
version = "3.72"
[Prereqs.perl.runtime.HTTP-Message]
version = "0"
[Prereqs.perl.runtime.XML-Simple]
version = "0"
