[Package]
category = "perl"
name = "Test-Distribution"
version = "2.00"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.ExtUtils-Manifest]
version = "1.70"
[Prereqs.perl.runtime.File-Find-Rule]
version = "0.34"
[Prereqs.perl.runtime.Module-CoreList]
version = "5.20160520"
[Prereqs.perl.runtime.Pod-Coverage]
version = "0.23"
[Prereqs.perl.runtime.Test-Pod]
version = "1.51"
[Prereqs.perl.runtime.Test-Pod-Coverage]
version = "1.10"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.test]
