[Package]
category = "perl"
name = "Exporter"
version = "5.72"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Carp]
version = "1.38"
[Prereqs.perl.runtime.Test-Pod]
version = "1.51"
[Prereqs.perl.runtime.Test-Pod-Coverage]
version = "1.10"
[Prereqs.perl.test]
