[Package]
category = "perl"
name = "Time-TZOffset"
version = "0.04"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Module-Build]
version = "0.4218"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
