[Package]
category = "perl"
name = "Pod-Strip"
version = "1.02"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Pod-Simple]
version = "3.32"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.test]
