[Package]
category = "perl"
name = "Module-CPANTS-Analyse"
version = "0.96"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker-CPANfile]
version = "0.07"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Archive-Any-Lite]
version = "0.11"
[Prereqs.perl.runtime.Archive-Tar]
version = "2.08"
[Prereqs.perl.runtime.Array-Diff]
version = "0.07"
[Prereqs.perl.runtime.CPAN-DistnameInfo]
version = "0.12"
[Prereqs.perl.runtime.CPAN-Meta]
version = "2.150005"
[Prereqs.perl.runtime.CPAN-Meta-YAML]
version = "0.018"
[Prereqs.perl.runtime.Class-Accessor]
version = "0.34"
[Prereqs.perl.runtime.File-Find-Object]
version = "v0.2.13"
[Prereqs.perl.runtime.IO-Capture]
version = "0.04"
[Prereqs.perl.runtime.JSON-MaybeXS]
version = "1.003005"
[Prereqs.perl.runtime.Module-ExtractUse]
version = "0.341"
[Prereqs.perl.runtime.Module-Pluggable]
version = "5.2"
[Prereqs.perl.runtime.Set-Scalar]
version = "1.29"
[Prereqs.perl.runtime.Software-License]
version = "0.103012"
[Prereqs.perl.runtime.Software-License-CCpack]
version = "1.11"
[Prereqs.perl.runtime.Text-Balanced]
version = "2.03"
[Prereqs.perl.runtime.version]
version = "0.9917"
[Prereqs.perl.test]
