[Package]
category = "perl"
name = "Net-DNS"
version = "1.06"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Digest-HMAC]
version = "1.03"
[Prereqs.perl.runtime.Digest-MD5]
version = "2.55"
[Prereqs.perl.runtime.Digest-SHA]
version = "5.95"
[Prereqs.perl.runtime.IO]
version = "1.25"
[Prereqs.perl.runtime.MIME-Base64]
version = "3.15"
[Prereqs.perl.runtime.PathTools]
version = "3.62"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.runtime.Time-Local]
version = "1.2300"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
