[Package]
category = "perl"
name = "Array-Diff"
version = "0.07"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Algorithm-Diff]
version = "1.1903"
[Prereqs.perl.runtime.Algorithm-Diff-XS]
version = "0.01"
[Prereqs.perl.runtime.Class-Accessor]
version = "0.34"
[Prereqs.perl.runtime.Filter]
version = "1.55"
[Prereqs.perl.test]
