[Package]
category = "perl"
name = "WWW-RobotRules"
version = "6.02"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.URI]
version = "1.71"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
