[Package]
category = "perl"
name = "Filter-Simple-Compile"
version = "0.02"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Module-Compile]
version = "0.35"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
