[Package]
category = "perl"
name = "Encode"
version = "2.84"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Exporter]
version = "5.72"
[Prereqs.perl.runtime.parent]
version = "0.234"
[Prereqs.perl.test]
