[Package]
category = "perl"
name = "File-Find-Rule"
version = "0.34"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Number-Compare]
version = "0.03"
[Prereqs.perl.runtime.PathTools]
version = "3.62"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.runtime.Text-Glob]
version = "0.09"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
