[Package]
category = "perl"
name = "Archive-Tar"
version = "2.10"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "0"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.IO-Compress]
version = "2.069"
[Prereqs.perl.runtime.IO-Zlib]
version = "1.10"
[Prereqs.perl.runtime.PathTools]
version = "3.62"
[Prereqs.perl.runtime.Test-Harness]
version = "3.36"
[Prereqs.perl.runtime.Test-Simple]
version = "0"
