[Package]
category = "perl"
name = "File-Which"
version = "1.21"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.configure.perl]
version = "5.024000"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.perl]
version = "5.024000"
