[Package]
category = "perl"
name = "Exporter-Tiny"
version = "0.042"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Fatal]
version = "0.014"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.Test-Warnings]
version = "0.026"
