[Package]
category = "perl"
name = "Catalyst-View-JSON"
version = "0.36"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Catalyst-Runtime]
version = "5.90104"
[Prereqs.perl.runtime.JSON-MaybeXS]
version = "1.003005"
[Prereqs.perl.runtime.MRO-Compat]
version = "0.12"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
