[Package]
category = "perl"
name = "B-C"
version = "1.54"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.B-Debug]
version = "1.23"
[Prereqs.perl.runtime.B-Flags]
version = "0.16"
[Prereqs.perl.runtime.IPC-Run]
version = "0.94"
[Prereqs.perl.runtime.Opcodes]
version = "0.14"
[Prereqs.perl.runtime.Time-HiRes]
version = "1.9733"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
