[Package]
category = "perl"
name = "Test-Harness"
version = "3.36"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Pod-Usage]
version = "1.69"
[Prereqs.perl.test]
