[Package]
category = "perl"
name = "Role-Tiny"
version = "2.000003"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Class-Method-Modifiers]
version = "2.12"
[Prereqs.perl.runtime.Exporter]
version = "5.72"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
