[Package]
category = "perl"
name = "IO-Compress"
version = "2.069"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Compress-Raw-Bzip2]
version = "2.069"
[Prereqs.perl.runtime.Compress-Raw-Zlib]
version = "2.069"
[Prereqs.perl.runtime.Scalar-List-Utils]
version = "1.45"
[Prereqs.perl.test]
