[Package]
category = "perl"
name = "Digest-MD5"
version = "2.55"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "0"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Digest]
version = "1.17"
