[Package]
category = "perl"
name = "Catalyst-Plugin-Session"
version = "0.40"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Catalyst-Runtime]
version = "5.90104"
[Prereqs.perl.runtime.Digest]
version = "1.17"
[Prereqs.perl.runtime.File-Temp]
version = "0.2304"
[Prereqs.perl.runtime.MRO-Compat]
version = "0.12"
[Prereqs.perl.runtime.Moose]
version = "2.1803"
[Prereqs.perl.runtime.MooseX-Emulate-Class-Accessor-Fast]
version = "0.00903"
[Prereqs.perl.runtime.Object-Signature]
version = "1.07"
[Prereqs.perl.runtime.PathTools]
version = "3.62"
[Prereqs.perl.runtime.Scalar-List-Utils]
version = "1.45"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.runtime.Tie-RefHash]
version = "1.39"
[Prereqs.perl.runtime.namespace-clean]
version = "0.27"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
