[Package]
category = "perl"
name = "Package-Pkg"
version = "0.0020"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Class-Load]
version = "0"
[Prereqs.perl.runtime.Clone]
version = "0"
[Prereqs.perl.runtime.Mouse]
version = "0"
[Prereqs.perl.runtime.Sub-Install]
version = "0"
[Prereqs.perl.runtime.Try-Tiny]
version = "0"
