[Package]
category = "perl"
name = "XML-SAX"
version = "0.99"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.File-Temp]
version = "0.2304"
[Prereqs.perl.runtime.XML-NamespaceSupport]
version = "1.11"
[Prereqs.perl.runtime.XML-SAX-Base]
version = "1.08"
[Prereqs.perl.test]
