[Package]
category = "perl"
name = "Config-JFDI"
version = "0.065"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Any-Moose]
version = "0"
[Prereqs.perl.runtime.Carp-Clan-Share]
version = "0"
[Prereqs.perl.runtime.Clone]
version = "0"
[Prereqs.perl.runtime.Config-Any]
version = "0"
[Prereqs.perl.runtime.Config-General]
version = "0"
[Prereqs.perl.runtime.Data-Visitor]
version = "0.30"
[Prereqs.perl.runtime.Getopt-Usaginator]
version = "0"
[Prereqs.perl.runtime.Hash-Merge-Simple]
version = "0"
[Prereqs.perl.runtime.List-MoreUtils]
version = "0"
[Prereqs.perl.runtime.Path-Class]
version = "0"
[Prereqs.perl.runtime.Sub-Install]
version = "0"
