[Package]
category = "perl"
name = "CatalystX-RoleApplicator"
version = "0.005"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.requires]
[Prereqs.perl.requires.Catalyst-Runtime]
version = "5.90112"
[Prereqs.perl.requires.Moose]
version = "2.1804"
[Prereqs.perl.requires.MooseX-RelatedClassRoles]
version = "0.004"
