[Package]
category = "perl"
name = "Facebook-Graph"
version = "1.1101"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.DateTime]
version = 1.39
[Prereqs.perl.runtime.DateTime-Format-Strptime]
version = "1.68"
[Prereqs.perl.runtime.JSON]
version = "2.90"
[Prereqs.perl.runtime.LWP-Protocol-https]
version = "6.06"
[Prereqs.perl.runtime.MIME-Base64-URLSafe]
version = "0.01"
[Prereqs.perl.runtime.Moo]
version = "0"
[Prereqs.perl.runtime.Ouch]
version = "0.0409"
[Prereqs.perl.runtime.URI]
version = "1.71"
[Prereqs.perl.runtime.libwww-perl]
version = "6.15"
