[Package]
category = "perl"
name = "CatalystX-RoleApplicator"
version = "0.005"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Catalyst-Runtime]
version = "5.90104"
[Prereqs.perl.runtime.Moose]
version = "2.1803"
[Prereqs.perl.runtime.MooseX-RelatedClassRoles]
version = "0.004"
[Prereqs.perl.test]
