[Package]
category = "perl"
name = "Tree-Simple-VisitorFactory"
version = "0.15"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.PathTools]
version = "3.62"
[Prereqs.perl.runtime.Scalar-List-Utils]
version = "1.45"
[Prereqs.perl.runtime.Tree-Simple]
version = "1.29"
[Prereqs.perl.runtime.base]
version = "2.23"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Exception]
version = "0.43"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
