[Package]
category = "perl"
name = "Filter"
version = "1.55"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Filter-Simple]
version = "0.91"
[Prereqs.perl.runtime.Filter-Simple-Compile]
version = "0.02"
[Prereqs.perl.test]
