[Package]
category = "perl"
name = "Moose"
version = "2.1803"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Dist-CheckConflicts]
version = "0.11"
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.configure.JSON-PP]
version = "2.27400"
[Prereqs.perl.configure.perl]
version = "5.024000"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Carp]
version = "1.38"
[Prereqs.perl.runtime.Class-Load]
version = "0.23"
[Prereqs.perl.runtime.Class-Load-XS]
version = "0.09"
[Prereqs.perl.runtime.Data-OptList]
version = "0.110"
[Prereqs.perl.runtime.Devel-GlobalDestruction]
version = "0.13"
[Prereqs.perl.runtime.Devel-OverloadInfo]
version = "0.004"
[Prereqs.perl.runtime.Devel-PartialDump]
version = "0.18"
[Prereqs.perl.runtime.Devel-StackTrace]
version = "2.01"
[Prereqs.perl.runtime.Dist-CheckConflicts]
version = "0.11"
[Prereqs.perl.runtime.Eval-Closure]
version = "0.14"
[Prereqs.perl.runtime.MRO-Compat]
version = "0.12"
[Prereqs.perl.runtime.Module-Runtime]
version = "0.014"
[Prereqs.perl.runtime.Module-Runtime-Conflicts]
version = "0.002"
[Prereqs.perl.runtime.Package-DeprecationManager]
version = "0.16"
[Prereqs.perl.runtime.Package-Stash]
version = "0.37"
[Prereqs.perl.runtime.Package-Stash-XS]
version = "0.28"
[Prereqs.perl.runtime.Params-Util]
version = "1.07"
[Prereqs.perl.runtime.Scalar-List-Utils]
version = "1.45"
[Prereqs.perl.runtime.Sub-Exporter]
version = "0.987"
[Prereqs.perl.runtime.Sub-Identify]
version = "0.12"
[Prereqs.perl.runtime.Sub-Name]
version = "0.15"
[Prereqs.perl.runtime.Try-Tiny]
version = "0.24"
[Prereqs.perl.runtime.parent]
version = "0.234"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.CPAN-Meta]
version = "2.150005"
[Prereqs.perl.test.CPAN-Meta-Check]
version = "0.012"
[Prereqs.perl.test.CPAN-Meta-Requirements]
version = "2.140"
[Prereqs.perl.test.Module-Metadata]
version = "1.000027"
[Prereqs.perl.test.PathTools]
version = "3.62"
[Prereqs.perl.test.Test-CleanNamespaces]
version = "0.18"
[Prereqs.perl.test.Test-Fatal]
version = "0.014"
[Prereqs.perl.test.Test-Requires]
version = "0.10"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.Test-Warnings]
version = "0.026"
