[Package]
category = "perl"
name = "Path-Tiny"
version = "0.094"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.configure.JSON-PP]
version = "2.27400"
[Prereqs.perl.configure.perl]
version = "5.024000"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Carp]
version = "1.38"
[Prereqs.perl.runtime.Digest]
version = "1.17"
[Prereqs.perl.runtime.Digest-SHA]
version = "5.95"
[Prereqs.perl.runtime.Exporter]
version = "5.72"
[Prereqs.perl.runtime.File-Path]
version = "2.12"
[Prereqs.perl.runtime.File-Temp]
version = "0.2304"
[Prereqs.perl.runtime.PathTools]
version = "3.62"
[Prereqs.perl.runtime.Unicode-UTF8]
version = "0.60"
[Prereqs.perl.runtime.constant]
version = "1.33"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.runtime.perl_mlb]
version = 0
[Prereqs.perl.test]
[Prereqs.perl.test.CPAN-Meta]
version = "2.150005"
[Prereqs.perl.test.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.test.File-Temp]
version = "0.2304"
[Prereqs.perl.test.PathTools]
version = "3.62"
[Prereqs.perl.test.Test-FailWarnings]
version = "0.008"
[Prereqs.perl.test.Test-MockRandom]
version = "1.01"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.lib]
version = "0.63"
[Prereqs.perl.test.perl]
version = "5.024000"
