[Package]
category = "perl"
name = "Module-CPANfile"
version = "1.1002"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.CPAN-Meta]
version = "2.150005"
[Prereqs.perl.runtime.JSON-PP]
version = "2.27400"
[Prereqs.perl.runtime.Pod-Usage]
version = "1.69"
[Prereqs.perl.runtime.parent]
version = "0.234"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
