[Package]
category = "perl"
name = "Filesys-Notify-Simple"
version = "0.12"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.File-Temp]
version = "0.2304"
[Prereqs.perl.test.Test-SharedFork]
version = "0.35"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
