[Package]
category = "perl"
name = "WWW-Pastebin-PastebinCom-Create"
version = "1.003"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Module-Build]
version = "0.4218"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Moo]
version = "2.001001"
[Prereqs.perl.runtime.WWW-Mechanize]
version = "1.75"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
