[Package]
category = "perl"
name = "parent"
version = "0.236"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "0"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Test-Simple]
version = "1.302059"
