[Package]
category = "perl"
name = "PPI"
version = "1.220"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Clone]
version = "0.38"
[Prereqs.perl.runtime.IO-String]
version = "1.08"
[Prereqs.perl.runtime.List-MoreUtils]
version = "0.416"
[Prereqs.perl.runtime.Params-Util]
version = "1.07"
[Prereqs.perl.runtime.Task-Weaken]
version = "0"
