[Package]
category = "perl"
name = "UNIVERSAL-can"
version = "1.20140328"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Scalar-List-Utils]
version = "1.45"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
