[Package]
category = "perl"
name = "version"
version = "0.9917"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime.File-Temp]
version = "0.2304"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.runtime.parent]
version = "0.234"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
