[Package]
category = "perl"
name = "Software-License-CCpack"
version = "1.11"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Software-License]
version = "0.103012"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.CPAN-Meta]
version = "2.150005"
[Prereqs.perl.test.Test-CheckDeps]
version = "0.010"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.perl]
version = "5.024000"
