[Package]
category = "perl"
name = "Parallel-Scoreboard"
version = "0.07"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Class-Accessor-Lite]
version = "0.08"
[Prereqs.perl.runtime.HTML-Parser]
version = "0"
[Prereqs.perl.runtime.JSON]
version = "0"
