[Package]
category = "perl"
name = "Catalyst-Plugin-ConfigLoader"
version = "0.34"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Catalyst-Runtime]
version = "5.90104"
[Prereqs.perl.runtime.Config-Any]
version = "0.27"
[Prereqs.perl.runtime.Data-Visitor]
version = "0.30"
[Prereqs.perl.runtime.MRO-Compat]
version = "0.12"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
