[Package]
category = "perl"
name = "Template-Toolkit"
version = "2.26"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.AppConfig]
version = "1.71"
[Prereqs.perl.runtime.File-Temp]
version = "0.2304"
[Prereqs.perl.runtime.PathTools]
version = "3.62"
[Prereqs.perl.runtime.Scalar-List-Utils]
version = "1.45"
[Prereqs.perl.runtime.Test-LeakTrace]
version = "0.15"
[Prereqs.perl.test]
