[Package]
category = "perl"
name = "Test-OpenID-Server"
version = "0.03"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.HTTP-Server-Simple]
version = "0"
[Prereqs.perl.runtime.Net-OpenID-Server]
version = "0"
[Prereqs.perl.runtime.Test-HTTP-Server-Simple]
version = "0"
[Prereqs.perl.runtime.Test-OpenID-Consumer]
version = "0"
[Prereqs.perl.runtime.Test-WWW-Mechanize]
version = "0"
