[Package]
category = "perl"
name = "Readonly"
version = "2.04"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Module-Build-Tiny]
version = "0.039"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
