[Package]
category = "perl"
name = "Devel-GlobalDestruction"
version = "0.13"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-CBuilder]
version = "0.280224"
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Sub-Exporter-Progressive]
version = "0.001011"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
