[Package]
category = "perl"
name = "Catalyst-Plugin-Authentication"
version = "0.10023"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Catalyst-Plugin-Session]
version = "0.40"
[Prereqs.perl.runtime.Catalyst-Runtime]
version = "0"
[Prereqs.perl.runtime.Class-Inspector]
version = "0"
[Prereqs.perl.runtime.MRO-Compat]
version = "0"
[Prereqs.perl.runtime.Moose]
version = "0"
[Prereqs.perl.runtime.MooseX-Emulate-Class-Accessor-Fast]
version = "0"
[Prereqs.perl.runtime.String-RewritePrefix]
version = "0"
[Prereqs.perl.runtime.Try-Tiny]
version = "0"
[Prereqs.perl.runtime.namespace-autoclean]
version = "0"
