[Package]
category = "perl"
name = "Mojolicious"
version = "6.62"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.IO-Socket-IP]
version = "0.37"
[Prereqs.perl.runtime.JSON-PP]
version = "2.27400"
[Prereqs.perl.runtime.Pod-Simple]
version = "3.32"
[Prereqs.perl.runtime.Time-Local]
version = "1.2300"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
