[Package]
category = "perl"
name = "CPAN-Faker"
version = "0.010"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.CPAN-Checksums]
version = "0"
[Prereqs.perl.runtime.Data-Section]
version = "0"
[Prereqs.perl.runtime.File-Next]
version = "0"
[Prereqs.perl.runtime.Getopt-Long-Descriptive]
version = "0"
[Prereqs.perl.runtime.Module-Faker]
version = "0.017"
[Prereqs.perl.runtime.Moose]
version = "0"
[Prereqs.perl.runtime.Sort-Versions]
version = "0"
[Prereqs.perl.runtime.Text-Template]
version = "0"
