[Package]
category = "perl"
name = "multidimensional"
version = "0.012"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.B-Hooks-OP-Check]
version = "0.19"
[Prereqs.perl.configure.CPAN-Meta]
version = "2.150005"
[Prereqs.perl.configure.ExtUtils-Depends]
version = "0.405"
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.B-Hooks-OP-Check]
version = "0.19"
[Prereqs.perl.runtime.Lexical-SealRequireHints]
version = "0.010"
[Prereqs.perl.runtime.XSLoader]
version = "0.20"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.lib]
version = "0.63"
