[Package]
category = "perl"
name = "Term-Size-Any"
version = "0.002"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Devel-Hide]
version = "0"
[Prereqs.perl.runtime.Term-Size-Perl]
version = "0"
