[Package]
category = "perl"
name = "App-Cache"
version = "0.37"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Class-Accessor-Chained]
version = "0"
[Prereqs.perl.runtime.File-Find-Rule]
version = "0"
[Prereqs.perl.runtime.File-HomeDir]
version = "0"
[Prereqs.perl.runtime.HTTP-Cookies]
version = "0"
[Prereqs.perl.runtime.Path-Class]
version = "0"
[Prereqs.perl.runtime.libwww-perl]
version = "0"
