[Package]
category = "perl"
name = "Config-INI-Reader-Ordered"
version = "0.020"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Config-INI]
version = "0.025"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.CPAN-Meta]
version = "2.150005"
[Prereqs.perl.test.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.test.PathTools]
version = "3.62"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.perl]
version = "5.024000"
