[Package]
category = "perl"
name = "Parse-RecDescent"
version = "1.967013"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.runtime.Text-Balanced]
version = "2.03"
[Prereqs.perl.test]
