[Package]
category = "perl"
name = "Digest-HMAC"
version = "1.03"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Digest-MD5]
version = "2.55"
[Prereqs.perl.runtime.Digest-SHA]
version = "5.95"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
