[Package]
category = "perl"
name = "Type-Tie"
version = "0.009"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Exporter-Tiny]
version = "0.042"
[Prereqs.perl.runtime.Hash-FieldHash]
version = "0.14"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Fatal]
version = "0.014"
[Prereqs.perl.test.Test-Requires]
version = "0.10"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
