[Package]
category = "perl"
name = "Plack-Middleware-ReverseProxy"
version = "0.15"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Plack]
version = "1.0039"
[Prereqs.perl.runtime.parent]
version = "0.234"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
