[Package]
category = "perl"
name = "Starman"
version = "0.4014"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Module-Build-Tiny]
version = "0.039"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Data-Dump]
version = "1.23"
[Prereqs.perl.runtime.HTTP-Date]
version = "6.02"
[Prereqs.perl.runtime.HTTP-Message]
version = "6.11"
[Prereqs.perl.runtime.HTTP-Parser-XS]
version = "0.17"
[Prereqs.perl.runtime.Net-Server]
version = "2.008"
[Prereqs.perl.runtime.Plack]
version = "1.0039"
[Prereqs.perl.runtime.Server-Starter]
version = "0.32"
[Prereqs.perl.runtime.Test-TCP]
version = "2.16"
[Prereqs.perl.runtime.parent]
version = "0.234"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Requires]
version = "0.10"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.libwww-perl]
version = "6.15"
