[Package]
category = "perl"
name = "HTML-Form"
version = "6.03"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Encode]
version = "2.84"
[Prereqs.perl.runtime.HTML-Parser]
version = "3.72"
[Prereqs.perl.runtime.HTTP-Message]
version = "6.11"
[Prereqs.perl.runtime.URI]
version = "1.71"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
