[Package]
category = "perl"
name = "File-Find-Rule-Perl"
version = "1.15"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.File-Find-Rule]
version = "0.34"
[Prereqs.perl.runtime.Params-Util]
version = "1.07"
[Prereqs.perl.runtime.Parse-CPAN-Meta]
version = "1.4417"
[Prereqs.perl.runtime.PathTools]
version = "3.62"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
