[Package]
category = "perl"
name = "Test-Differences"
version = "0.64"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Capture-Tiny]
version = "0.42"
[Prereqs.perl.runtime.Data-Dumper]
version = "2.154"
[Prereqs.perl.runtime.Test-Simple]
version = "1.302022"
[Prereqs.perl.runtime.Text-Diff]
version = "1.44"
[Prereqs.perl.test]
