[Package]
category = "perl"
name = "Apache-LogFormat-Compiler"
version = "0.33"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Module-Build]
version = "0.4218"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.POSIX-strftime-Compiler]
version = "0.41"
[Prereqs.perl.runtime.Time-Local]
version = "1.2300"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.HTTP-Message]
version = "6.11"
[Prereqs.perl.test.Test-MockTime]
version = "0.15"
[Prereqs.perl.test.Test-Requires]
version = "0.10"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.Try-Tiny]
version = "0.24"
[Prereqs.perl.test.URI]
version = "1.71"
