[Package]
category = "perl"
name = "Log-Any-Adapter-Callback"
version = "0.09"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.ExtUtils-MakeMaker]
version = "7.18"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.Log-Any]
version = "1.040"
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.IO]
version = "1.25"
[Prereqs.perl.test.PathTools]
version = "3.62"
[Prereqs.perl.test.Test-Simple]
version = "1.302022"
[Prereqs.perl.test.perl]
version = "5.024000"
