[Package]
category = "perl"
name = "Server-Starter"
version = "0.32"
[Prereqs]
[Prereqs.perl]
[Prereqs.perl.configure]
[Prereqs.perl.configure.Module-Build]
version = "0.4218"
[Prereqs.perl.runtime]
[Prereqs.perl.runtime.perl]
version = "5.024000"
[Prereqs.perl.test]
[Prereqs.perl.test.IO-Socket-IP]
version = "0.37"
[Prereqs.perl.test.Test-Requires]
version = "0.10"
[Prereqs.perl.test.Test-SharedFork]
version = "0.35"
[Prereqs.perl.test.Test-TCP]
version = "2.16"
